# Generated by Django 5.0.6 on 2024-05-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_registration', '0002_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('accelerometer_data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.user')),
            ],
        ),
    ]
