# Generated by Django 5.0.6 on 2024-05-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FallDetection',
        ),
    ]
