# Generated by Django 5.0 on 2024-07-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_connected',
            field=models.BooleanField(default=False),
        ),
    ]
