# Generated by Django 5.0.6 on 2024-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FallDetectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_num', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_activity', models.CharField(max_length=20)),
                ('accel_x', models.FloatField(default=0)),
                ('accel_y', models.FloatField(default=0)),
                ('accel_z', models.FloatField(default=0)),
            ],
        ),
    ]
