# Generated by Django 5.0.6 on 2024-05-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='falldetectiondata',
            name='accel_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='falldetectiondata',
            name='accel_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='falldetectiondata',
            name='accel_z',
            field=models.FloatField(default=0),
        ),
    ]
